version: 0.1

phases:
  install:
    commands:
      - gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - bundel install
      - jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://phillytech-jekylltest1
