version: 0.1

phases:
  install:
    commands:
      - gem install jekyll bundler
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - bundle install
      - bundle exec jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://phillytech-jekylltest1
